#타임리프 뷰 리졸브 설정
#타임리프에서 cache말고는 다 default값이다(안적어도 된다)
spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-location: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook

#톰캣 포트 변경
server:
  port: 8090